### ISSUE TITLE
Cannot recover from seed, Wallet Seed

### ISSUE THREAD

**Issue by fishera123** [dagcoin/dagcoin#1350] opened 2018-06-07 08:19 UTC
some users are getting this error: 
![image.png](https://images.zenhubusercontent.com/59495ad151aa2c305782412f/c8560021-fd8c-4409-b28d-f720d60a4c70)

error is reproducable in 1.4.5 wallet

**Comment by irinadoros** [comment] 2018-06-20 08:18
The problem is fixed in some previous release, that why we cannot reproduce it in new wallet.

**Closed** 2018-06-20 12:22 UTC
Labels: question
