### ISSUE TITLE
Password functionality does not work

### ISSUE THREAD

**Issue by vkolt** [dagcoin/dagcoin#148] opened 2017-08-01 15:36 UTC
1. Go to global preferences and switch on Request password. 
2. Create password and close application. 
3. Run application again
Error message appears

**Comment by vkolt** [comment] 2017-08-01 15:36
![Screen Shot 2017-08-01 at 18.21.15.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/595f9b04705d35001a11afd7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b772b6454f26b7191a379e70c2950415e4bbe5d4a1f06a3a3dc78e2a436628f550fe4d66d5c25933517a5b1d61fbf03bc73df4680b7e89850d2aa6c7bb3d4d216744b470a83ed5e34aa984ec859f04be04a52ac1b3264f43b.png)

**Comment by iaptsiauri** [comment] 2017-08-11 12:19
Fixed the initial error, but afterwards received the another exception which was caused by the `fundingNodeService`. Because of this reassigned the task

**Closed** 2017-08-24 08:51 UTC
Labels: bug, finished
